### ISSUE TITLE
Waze crashes after second run

### ISSUE THREAD

**Issue by hungerz** [copperhead/bugtracker#271]
After installation the first run works as expected but the second and other runs are crashing all the time.

Tested versions: 3.9.6.0, 3.9.8.0, 3.9.9.0, 4.0.0.2, 4.0.1.1, 4.1.0.1, 4.2.0.1

Tested on: 5X and 6P

```
--------- beginning of system
05-23 15:07:28.428  4788  6961 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.waze/.FreeMapAppActivity (has extras)} from uid 10012 on display 0
05-23 15:07:28.495  4788  6514 I ActivityManager: Start proc 17179:com.waze/u0a66 for activity com.waze/.FreeMapAppActivity
05-23 15:07:28.879 17179 17179 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10066 <<<<<<
05-23 15:07:28.883 17179 17179 D AndroidRuntime: CheckJNI is OFF
05-23 15:07:28.914 17179 17179 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
05-23 15:07:28.945 17179 17179 I Radio-JNI: register_android_hardware_Radio DONE
05-23 15:07:28.964 17179 17179 D AndroidRuntime: Calling main entry com.android.internal.os.ExecInit
05-23 15:07:28.967 17179 17179 I SamplingProfilerIntegration: Profiling disabled.
05-23 15:07:28.995  4788  4923 I ActivityManager: Config changes=480 {1.0 ?mcc?mnc en_US ldltr sw411dp w683dp h387dp 420dpi nrml land finger -keyb/v/h -nav/h s.23}
05-23 15:07:29.000  4788  6027 I InputReader: Reconfiguring input devices.  changes=0x00000004
05-23 15:07:29.000  4788  6027 I InputReader: Device reconfigured: id=7, name='synaptics_rmi4_i2c', size 1080x1920, orientation 1, mode 1, display id 0
05-23 15:07:29.010   374   374 E qdoverlay: Failed to call ioctl MSMFB_OVERLAY_SET err=Device or resource busy
05-23 15:07:29.011   374   374 E qdoverlay: MdssRot commit failed!
05-23 15:07:29.011   374   374 E qdoverlay: == Dump MdssRot start ==
05-23 15:07:29.012   374   374 E qdoverlay: == Dump OvFD fd=90 path=/dev/graphics/fb0 start/end ==
05-23 15:07:29.013   374   374 E qdoverlay: == Dump OvMem start ==
05-23 15:07:29.013   374   374 E qdoverlay: fd=-1 addr=0xffffffffffffffff type=0 bufsz=0 AlignedBufSz=3755991007
05-23 15:07:29.013   374   374 E qdoverlay: == Dump OvMem end ==
05-23 15:07:29.014   374   374 E qdoverlay: mRotInfo mdp_overlay z=0 alpha=0 mask=0 flags=0x100084 id=-1
05-23 15:07:29.014   374   374 E qdoverlay: src msmfb_img w=1152 h=1920 format=5 MDP_RGB_888
05-23 15:07:29.014   374   374 E qdoverlay: src_rect mdp_rect x=0 y=0 w=1080 h=1080
05-23 15:07:29.015   374   374 E qdoverlay: dst_rect mdp_rect x=0 y=0 w=1080 h=1080
05-23 15:07:29.015   374   374 E qdoverlay: mRotData msmfb_overlay_data id=0
05-23 15:07:29.016   374   374 E qdoverlay: data msmfb_data offset=0 memid=-1 id=0 flags=0x0 priv=0
05-23 15:07:29.016   374   374 E qdoverlay: == Dump MdssRot end ==
05-23 15:07:29.016   374   374 E qdhwcomposer: configure: configRotator failed!
05-23 15:07:29.036 17179 17179 I MultiDex: VM with version 2.1.0 has multidex support
05-23 15:07:29.037 17179 17179 I MultiDex: install
05-23 15:07:29.037 17179 17179 I MultiDex: VM has multidex support, MultiDex support library is disabled.
05-23 15:07:29.049  4788  7719 I ActivityManager: START u0 {cmp=com.waze/.MainActivity} from uid 10066 on display 0
05-23 15:07:29.158 17179 17179 D TypefaceImpl: makeFontCollection adding /system/fonts/Roboto-Regular.ttf
05-23 15:07:29.200 17179 17179 E Minikin : addFont failed to create font /system/fonts/NanumGothic.ttf
05-23 15:07:29.201 17179 17179 E Minikin : addFont failed to create font /system/fonts/DroidSansFallback.ttf
05-23 15:07:29.202 17179 17179 E Minikin : addFont failed to create font /system/fonts/MTLmr3m.ttf
05-23 15:07:29.229  4788  4952 I WindowManager: Screen frozen for +246ms due to Window{22bcdd3 u0 NavigationBar}
05-23 15:07:29.303 17179 17179 E EmojiFactory_jni: Failed to load libemoji.so: dlopen failed: library "libemoji.so" not found
05-23 15:07:29.485 17179 17179 I WAZE.STOPWATCH APP START: $ MainActivity setContentView $. Delta: 447
05-23 15:07:29.485 17179 17179 I WAZE.STOPWATCH APP START: $ NativeManager Start $. Delta: 447
05-23 15:07:29.487 17179 17212 W WAZE    : Native thread is running
05-23 15:07:29.489 17179 17179 I WAZE.STOPWATCH APP START: $ NativeManager Start After wait $. Delta: 451
05-23 15:07:29.489 17179 17179 D WAZE    : Before changing native thread priority, current priority is 0
05-23 15:07:29.491 17179 17212 D WAZE    : Resources extraction unnecessary
05-23 15:07:29.497 17179 17212 I WAZE.STOPWATCH APP START: $ START $. Delta: 459
05-23 15:07:29.523 17179 17179 D WAZE.FBWrapper: New session created. Current state: CREATED
05-23 15:07:29.524 17179 17179 I WAZE.STOPWATCH APP START: $ MainActivity onCreate ENDED $. Delta: 485
05-23 15:07:29.524 17179 17212 I WAZE    : cryptowz Library is loaded
05-23 15:07:29.526 17179 17179 W WAZE DEBUG: ON RESUME. Task id: 61
05-23 15:07:29.527 17179 17179 D WAZE    : Previous active activity: null
05-23 15:07:29.527 17179 17179 D WAZE    : Current active activity: class com.waze.MainActivity
05-23 15:07:29.530 17179 17179 I WAZE.STOPWATCH APP START: $ MapView onResume $. Delta: 492
05-23 15:07:29.530 17179 17179 W WAZE    : MapView onResume
05-23 15:07:29.536 17179 17216 W GooglePlayServicesUtil: Google Play services is missing.
05-23 15:07:29.536 17179 17179 W GooglePlayServicesUtil: Google Play services is missing.
05-23 15:07:29.536 17179 17212 I WAZE    : sslwz Library is loaded
05-23 15:07:29.537 17179 17216 E ActivityThread: Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
05-23 15:07:29.548 17179 17218 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
05-23 15:07:29.556 17179 17179 I WAZE.STOPWATCH APP START: $ Service onCreate $. Delta: 518
05-23 15:07:29.559 17179 17179 I WAZE    : Available space at /storage/emulated/0: 25956462592
05-23 15:07:29.561 17179 17212 I WAZE    : sqlite Library is loaded
05-23 15:07:29.563 17179 17179 D WAZE_PIONEER: Pioneer app mode enabled - will start when Waze will be fully initialized.
05-23 15:07:29.565 17179 17179 I WAZE_Service: Service Created. Instance: com.waze.AppService@1593474
05-23 15:07:29.574 17179 17216 E WAZE    : com.waze.MainActivity@4686212
05-23 15:07:29.578 17179 17179 I WAZE_Service: Start service is called com.waze.AppService@1593474
--------- beginning of crash
05-23 15:07:29.580 17179 17216 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-23 15:07:29.580 17179 17216 E AndroidRuntime: Process: com.waze, PID: 17179
05-23 15:07:29.580 17179 17216 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "SSL_set_mode" referenced by "/system/lib/libjavacrypto.so"...
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at java.lang.Runtime.loadLibrary(Runtime.java:394)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1076)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at com.android.org.conscrypt.NativeCryptoJni.init(NativeCryptoJni.java:25)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at com.android.org.conscrypt.NativeCrypto.<clinit>(NativeCrypto.java:53)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at com.android.org.conscrypt.NativeCrypto.EVP_get_digestbyname(Native Method)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at com.android.org.conscrypt.OpenSSLMessageDigestJDK$SHA1.<clinit>(OpenSSLMessageDigestJDK.java:104)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at java.lang.Class.forName(Class.java:324)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at java.security.Provider$Service.newInstance(Provider.java:1072)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:141)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at java.security.MessageDigest.getInstance(MessageDigest.java:91)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at com.facebook.internal.Utility.hashWithAlgorithm(Utility.java:382)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at com.facebook.internal.Utility.hashWithAlgorithm(Utility.java:376)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at com.facebook.internal.Utility.sha1hash(Utility.java:368)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at com.facebook.internal.Utility.getHashedDeviceAndAppID(Utility.java:834)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at com.facebook.Settings.publishInstallAndWaitForResponse(Settings.java:388)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at com.facebook.Settings$2.run(Settings.java:326)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-23 15:07:29.580 17179 17216 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
05-23 15:07:29.584  4788 14805 W ActivityManager:   Force finishing activity com.waze/.MainActivity
05-23 15:07:29.620 17179 17212 I WAZE    : Waze Library is loaded
05-23 15:07:29.627  4788  6054 I OpenGLRenderer: Initialized EGL, version 1.4
05-23 15:07:29.678 17179 17218 D libEGL  : loaded /vendor/lib/egl/libEGL_adreno.so
05-23 15:07:29.779 17179 17218 D libEGL  : loaded /vendor/lib/egl/libGLESv1_CM_adreno.so
05-23 15:07:29.789 17179 17212 D WAZE    : init install nm ready=false
05-23 15:07:29.789 17179 17218 D libEGL  : loaded /vendor/lib/egl/libGLESv2_adreno.so
05-23 15:07:29.789 17179 17212 D WAZE    : initNativeLayerNTV 13
05-23 15:07:29.790 17179 17212 D WAZE    : ctr running in thread 13
05-23 15:07:29.796 17179 17212 D WAZE    : init driveto ready=false
05-23 15:07:29.796 17179 17212 D WAZE    : initNativeLayerNTV 13
05-23 15:07:29.797 17179 17212 D WAZE    : ctr running in thread 13
05-23 15:07:29.922 17179 17218 I Adreno  : QUALCOMM build                   : 63c06b2, I8366cd0437
05-23 15:07:29.922 17179 17218 I Adreno  : Build Date                       : 12/06/15
05-23 15:07:29.922 17179 17218 I Adreno  : OpenGL ES Shader Compiler Version: XE031.05.13.02
05-23 15:07:29.922 17179 17218 I Adreno  : Local Branch                     : mybranch17112971
05-23 15:07:29.922 17179 17218 I Adreno  : Remote Branch                    : quic/LA.BF64.1.2.9_v2
05-23 15:07:29.922 17179 17218 I Adreno  : Remote Branch                    : NONE
05-23 15:07:29.922 17179 17218 I Adreno  : Reconstruct Branch               : NOTHING
05-23 15:07:29.931 17179 17218 I OpenGLRenderer: Initialized EGL, version 1.4
05-23 15:07:29.966 17179 17179 W WAZE    : MapView Surface changed: 1794, 1017.
05-23 15:07:29.967 17179 17179 I WAZE.STOPWATCH APP START: $ MapView surfaceChanged $. Delta: 929
05-23 15:07:29.998 17179 17205 W WAZE    : OGL RENDERER SURFACE CREATED
05-23 15:07:30.000 17179 17205 E Frame Buffer: renderer : Adreno (TM) 418
05-23 15:07:30.007 17179 17205 W WAZE    : OGL RENDERER SURFACE CHANGED ( 1794 , 1017 )
05-23 15:07:30.009 17179 17205 I WAZE.STOPWATCH APP START: $ OGLRenderer onSurfaceChanged $. Delta: 971
05-23 15:07:30.045 17179 17212 D WAZE.BackLight: Always on value: 1
05-23 15:07:30.087  4788  4939 W ActivityManager: Activity pause timeout for ActivityRecord{e813e38 u0 com.waze/.MainActivity t61 f}
05-23 15:07:30.124  4788  4939 I ActivityManager: Config changes=480 {1.0 ?mcc?mnc en_US ldltr sw411dp w411dp h659dp 420dpi nrml port finger -keyb/v/h -nav/h s.24}
05-23 15:07:30.151  4788  6027 I InputReader: Reconfiguring input devices.  changes=0x00000004
05-23 15:07:30.151  4788  6027 I InputReader: Device reconfigured: id=7, name='synaptics_rmi4_i2c', size 1080x1920, orientation 0, mode 1, display id 0
05-23 15:07:30.190 17179 17179 W WAZE    : MapView onPause
05-23 15:07:30.215 17179 17179 W WAZE DEBUG: MapView Surface destroyed
05-23 15:07:30.217 17179 17179 W WAZE DEBUG: After MapView Surface destroyed
05-23 15:07:30.220 17179 17179 I WAZE.STOPWATCH APP START: $ MapView surfaceChangedCompleted $. Delta: 1182
05-23 15:07:30.221 17179 17179 W WAZE    : MapView Surface changed completed
05-23 15:07:30.249  4788  4952 W WindowManager: Failed looking up window
05-23 15:07:30.249  4788  4952 W WindowManager: java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@6e9d94c does not exist
05-23 15:07:30.249  4788  4952 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8718)
05-23 15:07:30.249  4788  4952 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8709)
05-23 15:07:30.249  4788  4952 W WindowManager:         at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2697)
05-23 15:07:30.249  4788  4952 W WindowManager:         at com.android.server.wm.Session.remove(Session.java:187)
05-23 15:07:30.249  4788  4952 W WindowManager:         at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3107)
05-23 15:07:30.249  4788  4952 W WindowManager:         at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5616)
05-23 15:07:30.249  4788  4952 W WindowManager:         at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3417)
05-23 15:07:30.249  4788  4952 W WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:102)
05-23 15:07:30.249  4788  4952 W WindowManager:         at android.os.Looper.loop(Looper.java:148)
05-23 15:07:30.249  4788  4952 W WindowManager:         at android.os.HandlerThread.run(HandlerThread.java:61)
05-23 15:07:30.249  4788  4952 W WindowManager:         at com.android.server.ServiceThread.run(ServiceThread.java:46)
05-23 15:07:30.250 17179 17179 D WAZE    : Shutdown manager - all the activities are destroyed
05-23 15:07:30.472  4788  4952 I WindowManager: Screen frozen for +364ms due to Window{554c973 u0 com.android.systemui.ImageWallpaper}
05-23 15:07:31.234  4788 16850 D NetlinkSocketObserver: NeighborEvent{elapsedMs=174180185, 123.123.123.123, [00155D04870D], RTM_NEWNEIGH, NUD_STALE}
05-23 15:07:31.510 17179 17216 I Process : Sending signal. PID: 17179 SIG: 9
05-23 15:07:31.519  4788  7085 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@22109ba attribute=null, token = android.os.BinderProxy@b67e8ec
05-23 15:07:31.538  4788 14805 D GraphicsStats: Buffer count: 4
05-23 15:07:31.544  4788  4922 I ActivityManager: Process com.waze (pid 17179) has died
05-23 15:07:31.545  4788  4922 W ActivityManager: Scheduling restart of crashed service com.waze/.AppService in 1000ms
05-23 15:07:31.552  4788  6690 E LocSvc_ApiV02: E/virtual loc_api_adapter_err LocApiV02::stopFix():531]: Error : st = 0, ind.status = 1
05-23 15:07:31.705  4788  4952 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
```

**Comment by thestinger** [comment]
Can you try this again with the latest releases?

**Comment by hungerz** [comment]
Same results but with earlier releases I found a Waze version which work on second run too. This is 3.9.9.906 and needs Contacts (and of course Location) permissions. The other versions still crash (with full permissions too).

**Comment by vbokan** [comment]
A bit offtopic but googling for "qdoverlay: MdssRot commit failed!" got me here.

Same problem with 5X and 6P running Nougat happening on rotation. Possibly something on Android/HW end is faulty.

**Comment by thestinger** [comment]
Needs to be confirmed again on Android Nougat.
