### ISSUE TITLE
SprintDM breaks due to not finding a required class

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#329]
Have received reports of Sprint support not working, due to SprintDM throwing errors when it fails to find a required class. It's not clear why this happens or if it even happens consistently happens for all Sprint users.

Difficult to debug it without a way to test it directly.

**Comment by thestinger** [comment]
This doesn't appear to be caused by https://github.com/anestisb/android-prepare-vendor/issues/12 after all.

**Comment by jgmoss** [comment]
I'm experiencing this bug on my Nexus 6P.

**Comment by thestinger** [comment]
Can't really work on this without access to Sprint though. Hoping that someone steps up to contribute, but not optimistic about that, so it's unlikely this will be fixed.

**Comment by thestinger** [comment]
Not sure what the problem could be anyway. It seems like android-prepare-vendor doesn't output a working app, rather than a problem with CopperheadOS itself.

**Comment by jgmoss** [comment]
I'm not a programmer, but is there anything I can do to help? Some sort of log file, or something else, that may be of help?

**Comment by thestinger** [comment]
Have a useful log from someone already, but there's no obvious problem. Need a contributor willing to invest time in figuring out what's wrong with it, not planning on working on it myself anytime soon (lots of other work to do):

```
07-02 13:41:43.339  4833  5176 I ActivityManager: START u0 {act=android.intent.action.MAIN cmp=com.android.sdm.plugins.sprintdm/.SprintUpdateDeviceConfigActivity} from uid 1001 on display 0
07-02 13:41:43.348  4833  9094 E NdkMediaExtractor: sf error code: -1010
07-02 13:41:43.349  4833  9094 E SoundPool: Unable to load sample
07-02 13:41:43.349  4833  9094 E NdkMediaExtractor: sf error code: -1010
07-02 13:41:43.350  4833  9094 E SoundPool: Unable to load sample
07-02 13:41:43.350  4833  9094 E NdkMediaExtractor: sf error code: -1010
07-02 13:41:43.350  4833  6970 W AudioService: onLoadSoundEffects(), Error -10000 while loading samples
07-02 13:41:43.351  4833  9094 E SoundPool: Unable to load sample
07-02 13:41:43.368  9067  9067 D SprintUpdateDeviceConfigActivity: showing update DC dialog
07-02 13:41:43.482  9067  9067 D SprintUpdateDeviceConfigActivity: starting client initiated DC
07-02 13:41:43.577  9067  9067 D SprintDMService: SprintDMService constructed [tid=1]
07-02 13:41:43.579  9067  9067 D SprintDMService: onStartCommand: intent="Intent { act=com.android.sprintdm.action.START_CIDC cmp=com.android.sdm.plugins.sprintdm/.SprintDMService }" [tid=1]
07-02 13:41:43.580  9067  9067 D SprintDMService: onStartCommand: action="com.android.sprintdm.action.START_CIDC" flags=0 startId=1
07-02 13:41:43.581  9067  9067 D SprintDMService: User is requesting CIDC.
07-02 13:41:43.599  9067  9067 D RadioConfigCommands: new RadioConfigCommands(com.android.sdm.plugins.sprintdm.SprintDMService@9c080f9)
07-02 13:41:43.610  9067  9067 D QC_RIL_OEM_HOOK: Starting QcrilMsgTunnel Service
07-02 13:41:43.614  9067  9067 D QC_RIL_OEM_HOOK: The QcrilMsgTunnelService will be connected soon
07-02 13:41:43.615  9067  9067 D QC_RIL_OEM_HOOK: Registering for intent ACTION_UNSOL_RESPONSE_OEM_HOOK_RAW
07-02 13:41:43.621  9067  9067 D SprintDMHelper: simOperator: 310120
07-02 13:41:43.621  9067  9067 D SprintDMHelper: isUICCSprint: We have a Sprint UICC
07-02 13:41:43.628  9067  9067 D SprintDMStateMachine: Last run due to: UICC ID changed from: to: 89011201000380717890
07-02 13:41:43.668  9067  9067 D SprintDMStateMachine: clearing HFA flags
07-02 13:41:43.670  9067  9067 D SprintDMStateMachine: getNextHfaState: PerformDeviceConfigState
07-02 13:41:43.671  9067  9096 D SprintDMStateMachine: CIDC: start HFA session
07-02 13:41:43.671  9067  9096 D SprintDMStateMachine: startHfaDeviceConfig()
07-02 13:41:43.696  9067  9096 D SprintDMStateMachine: starting FOTA session with alert string [Ljava.lang.String;@a80fbab
07-02 13:41:43.709  4833  5183 I ActivityManager: Start proc 9099:com.android.omadm.service/u0a5 for broadcast com.android.omadm.service/.DMIntentReceiver
07-02 13:41:43.722  9067  9096 D SprintDMStateMachine: PerformDeviceConfigState: processMessage EVENT_PERFORM_USER_CIDC
07-02 13:41:43.723  9067  9096 D SprintDMStateMachine: perform user CIDC session
07-02 13:41:43.724  9067  9096 D SprintDMStateMachine: starting FOTA session with alert string [Ljava.lang.String;@6db7208
07-02 13:41:43.814  4833  5177 I ActivityManager: Killing 8103:com.android.managedprovisioning/u0a14 (adj 15): empty #17
07-02 13:41:43.814  9099  9099 D AndroidRuntime: Shutting down VM
07-02 13:41:43.818  9067  9067 D QC_RIL_OEM_HOOK: QcrilMsgTunnelService Connected Successfully (onServiceConnected)
07-02 13:41:43.819  9067  9067 D QC_RIL_OEM_HOOK: Calling onQcRilHookReady callback
07-02 13:41:43.819  9067  9067 D OemHookWrapper: onQcRilHookReady()
07-02 13:41:43.838  4833  5226 I ActivityManager: Displayed com.android.sdm.plugins.sprintdm/.SprintUpdateDeviceConfigActivity: +479ms
07-02 13:41:43.843  9099  9099 E AndroidRuntime: FATAL EXCEPTION: main
07-02 13:41:43.843  9099  9099 E AndroidRuntime: Process: com.android.omadm.service, PID: 9099
07-02 13:41:43.843  9099  9099 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate receiver com.android.omadm.service.DMIntentReceiver: java.lang.ClassNotFoundException: Didn't find class "com.android.omadm.service.DMIntentReceiver" on path: DexPathList[[zip file "/system/priv-app/DMService/DMService.apk"],nativeLibraryDirectories=[/system/priv-app/DMService/lib/arm, /system/priv-app/DMService/DMService.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2706)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at android.app.ActivityThread.-wrap14(ActivityThread.java)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5422)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:721)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
07-02 13:41:43.843  9099  9099 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.omadm.service.DMIntentReceiver" on path: DexPathList[[zip file "/system/priv-app/DMService/DMService.apk"],nativeLibraryDirectories=[/system/priv-app/DMService/lib/arm, /system/priv-app/DMService/DMService.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2701)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        ... 8 more
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        Suppressed: java.io.IOException: No original dex files found for dex location /system/priv-app/DMService/DMService.apk
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at dalvik.system.DexFile.openDexFileNative(Native Method)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at dalvik.system.DexFile.openDexFile(DexFile.java:295)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at dalvik.system.DexFile.<init>(DexFile.java:80)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at dalvik.system.DexFile.<init>(DexFile.java:59)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at dalvik.system.DexPathList.loadDexFile(DexPathList.java:279)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at dalvik.system.DexPathList.<init>(DexPathList.java:120)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at android.app.LoadedApk.getClassLoader(LoadedApk.java:376)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at android.app.LoadedApk.makeApplication(LoadedApk.java:568)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4685)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                ... 6 more
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        Suppressed: java.lang.ClassNotFoundException: com.android.omadm.service.DMIntentReceiver
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at java.lang.Class.classForName(Native Method)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-02 13:41:43.843  9099  9099 E AndroidRuntime:                ... 10 more
07-02 13:41:43.843  9099  9099 E AndroidRuntime:        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-02 13:41:43.847  9067  9079 D OpenGLRenderer: endAllStagingAnimators on 0x7ee8e4c400 (ListView) with handle 0x7edc173cc0
07-02 13:41:43.857  9067  9067 W System  : ClassLoader referenced unknown path: /system/app/HiddenMenu/lib/arm64
07-02 13:41:43.864  9067  9067 D HfaBroadcastReceiver: onReceive com.android.sprintdm.status
07-02 13:41:43.901  4833  6833 I OpenGLRenderer: Initialized EGL, version 1.4
07-02 13:41:44.079   371   371 W SurfaceFlinger: couldn't log to binary event log: overflow.
07-02 13:41:45.929  9099  9099 I Process : Sending signal. PID: 9099 SIG: 9
07-02 13:41:45.932  4833  9120 E NdkMediaExtractor: sf error code: -1010
07-02 13:41:45.935  4833  6833 D OpenGLRenderer: endAllStagingAnimators on 0x7ed6fbf800 (RippleDrawable) with handle 0x7ed6ed4640
07-02 13:41:45.935  4833  9120 E SoundPool: Unable to load sample
07-02 13:41:45.936  4833  6970 W AudioService: onLoadSoundEffects(), Error -10000 while loading samples
07-02 13:41:45.936  4833  9120 E NdkMediaExtractor: sf error code: -1010
07-02 13:41:45.937  4833  9120 E SoundPool: Unable to load sample
07-02 13:41:45.957  4833  8356 I ActivityManager: Process com.android.omadm.service (pid 9099) has died
07-02 13:41:45.963  9067  9067 D HfaBroadcastReceiver: onReceive com.android.sprintdm.status
07-02 13:41:46.109  4833  5226 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
07-02 13:41:48.012  4833  6965 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 100] to 60
07-02 13:41:54.759  9067  9067 D SprintUpdateDeviceConfigActivity: sending ACTION_HFA_CANCEL
07-02 13:41:54.764  4833  9131 E NdkMediaExtractor: sf error code: -1010
07-02 13:41:54.764  4833  9131 E SoundPool: Unable to load sample
07-02 13:41:54.765  4833  6970 W AudioService: onLoadSoundEffects(), Error -10000 while loading samples
07-02 13:41:54.765  4833  9131 E NdkMediaExtractor: sf error code: -1010
07-02 13:41:54.766  4833  9131 E SoundPool: Unable to load sample
07-02 13:41:54.774  9067  9067 D SprintDMService: onStartCommand: intent="Intent { act=com.android.action.CANCEL_HFA cmp=com.android.sdm.plugins.sprintdm/.SprintDMService }" [tid=1]
07-02 13:41:54.774  9067  9067 D SprintDMService: onStartCommand: action="com.android.action.CANCEL_HFA" flags=0 startId=2
07-02 13:41:54.775  9067  9067 D SprintDMService: User cancelled HFA.
07-02 13:41:54.775  9067  9096 D SprintDMStateMachine: PerformDeviceConfigState: processMessage unknown event 25
07-02 13:41:54.775  9067  9096 D SprintDMStateMachine: cancellig DM session
07-02 13:41:54.776  9067  9067 D SprintDMService: service stopping at ID 2
07-02 13:41:54.789  4833  5183 I ActivityManager: Start proc 9133:com.android.omadm.service/u0a5 for broadcast com.android.omadm.service/.DMIntentReceiver
07-02 13:41:54.796  9067  9067 D SprintDMService: SprintDMService.onDestroy() called. [tid=1]
07-02 13:41:54.796  9067  9067 D SprintDMService: finished onDestroy()
07-02 13:41:54.797  9067  9096 D SprintDMStateMachine: IdleState: processMessage EVENT_ON_SERVICE_DESTROY
07-02 13:41:54.797  9067  9096 D SprintDMStateMachine: BaseState: halting state machine
07-02 13:41:54.812  4833  7057 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@4857f15 attribute=null, token = android.os.BinderProxy@e27a0d
07-02 13:41:54.850  9133  9133 D AndroidRuntime: Shutting down VM
07-02 13:41:54.851  9133  9133 E AndroidRuntime: FATAL EXCEPTION: main
07-02 13:41:54.851  9133  9133 E AndroidRuntime: Process: com.android.omadm.service, PID: 9133
07-02 13:41:54.851  9133  9133 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate receiver com.android.omadm.service.DMIntentReceiver: java.lang.ClassNotFoundException: Didn't find class "com.android.omadm.service.DMIntentReceiver" on path: DexPathList[[zip file "/system/priv-app/DMService/DMService.apk"],nativeLibraryDirectories=[/system/priv-app/DMService/lib/arm, /system/priv-app/DMService/DMService.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2706)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at android.app.ActivityThread.-wrap14(ActivityThread.java)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5422)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:721)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
07-02 13:41:54.851  9133  9133 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.omadm.service.DMIntentReceiver" on path: DexPathList[[zip file "/system/priv-app/DMService/DMService.apk"],nativeLibraryDirectories=[/system/priv-app/DMService/lib/arm, /system/priv-app/DMService/DMService.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2701)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        ... 8 more
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        Suppressed: java.io.IOException: No original dex files found for dex location /system/priv-app/DMService/DMService.apk
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at dalvik.system.DexFile.openDexFileNative(Native Method)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at dalvik.system.DexFile.openDexFile(DexFile.java:295)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at dalvik.system.DexFile.<init>(DexFile.java:80)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at dalvik.system.DexFile.<init>(DexFile.java:59)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at dalvik.system.DexPathList.loadDexFile(DexPathList.java:279)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at dalvik.system.DexPathList.<init>(DexPathList.java:120)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at android.app.LoadedApk.getClassLoader(LoadedApk.java:376)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at android.app.LoadedApk.makeApplication(LoadedApk.java:568)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4685)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                ... 6 more
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        Suppressed: java.lang.ClassNotFoundException: com.android.omadm.service.DMIntentReceiver
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at java.lang.Class.classForName(Native Method)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-02 13:41:54.851  9133  9133 E AndroidRuntime:                ... 10 more
07-02 13:41:54.851  9133  9133 E AndroidRuntime:        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-02 13:41:54.857  4833  5177 W ActivityManager: Process com.android.omadm.service has crashed too many times: killing!
07-02 13:41:54.859  4833  5177 I ActivityManager: Killing 9133:com.android.omadm.service/u0a5 (adj 9): crash
07-02 13:41:54.888  4833  7057 W ActivityManager: Spurious death for ProcessRecord{b33daf7 0:com.android.omadm.service/u0a5}, curProc for 9133: null
07-02 13:41:55.119   371   371 W SurfaceFlinger: couldn't log to binary event log: overflow.
0
```

**Comment by thestinger** [comment]
Also hard to work on something without any access to Sprint, since there's no straightforward way to test it.

**Comment by jgmoss** [comment]
I understand. Thanks for your work.

**Comment by thestinger** [comment]
It might simply be broken with AOSP + android-prepare-vendor. Checked to see if it was related to exec spawning and it wasn't, so there's a very low chance of an actual CopperheadOS feature causing this. Google doesn't have a fully supported way to do builds for their devices anymore so stuff like this may simply not work properly without spending more energy on simply working to make AOSP match stock more closely. Not one of the things that I spend time on, since I expect to be able to rely on AOSP or at least other people solving the same problems.

**Comment by biotinker** [comment]
I'm having this issue as well. I'm willing to put some work into solving this.

I did some research, it looks like Chroma had the same issue and the dev solved it, I'll send them a message asking what they did. http://forum.xda-developers.com/nexus-6p/development/rom-chroma-11-08-2015-lockscreen-navbar-t3244444

**Comment by biotinker** [comment]
The class that it seems to be missing appears to be available here:
http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android-apps/5.0.0_r1/com/android/omadm/service/DMIntentReceiver.java

**Comment by biotinker** [comment]
Some more information:
I went on a search for com.android.omadm.service.DMIntentReceiver, the class that appears to be missing.
I mounted the system.img files for both stock and Copperhead. Stock had this file that Copperhead did NOT have: etc/sysconfig/whitelist_com.android.omadm.service.xml

Additionally, Stock has the following app that Copperhead lacks: app/DMAgent/DMAgent.apk

I grepped DMIntentReceiver in both, and found that in Stock, the match was here:
Binary file ./priv-app/DMService/oat/arm/DMService.odex matches
but in Copperhead, it's here:
Binary file ./priv-app/DMService/oat/arm64/DMService.odex matches
I'm not sure how much the arm vs arm64 will matter.

**Comment by biotinker** [comment]
Later today I'll set up building the whole thing from source, and start trying swapping out various components that look different to see if I can get the thing to build and work properly.

**Comment by darknetj** [comment]
@biotinker thank you for helping us with this issue

**Comment by thestinger** [comment]
Perhaps DMService simply has to be 32-bit for this to work, since code using it might be 32-bit.

**Comment by biotinker** [comment]
I tried swapping out the contents of /system/priv-app/DMService/ in a fresh Copperhead install with the same folder from Stock, but no luck, same error.

**Comment by biotinker** [comment]
By the way, I suspect you'll need to include /system/app/Tycho/ if you ever want Project Fi to work properly

**Comment by biotinker** [comment]
I'm starting to run out of ideas.

It looks like the whole thing goes back to the com.android.omadm package, and it being absent and/or incomplete in Copperhead. Unfortunately, I can't actually find any documentation whatsoever on the package aside from a general overview of what it does, and I can't find any code relating to it newer than Android 5.0.0.

Anyone else have further suggestions for moving forward?

**Comment by biotinker** [comment]
Searching the string "DMIntentReceiver" against a full checkout of the OS yields no results, so I'm suspecting it's definitely something critical that's missing, rather than something simpler such as a 32/64 bit mismatch.

**Comment by thestinger** [comment]
I looked before and couldn't find anything related to that class that's missing.

**Comment by biotinker** [comment]
Possibly it's a bad version of DMService itself- it looks like the package it's claiming to be the problem, com.android.omadm.service, IS in fact DMService. But, it apparently doesn't contain the required method, and the latest code I can find publicly available that does is a whole major android version behind.

I'll keep searching though, and keep updating this thread with what I discover.

**Comment by thestinger** [comment]
It's proprietary code from the latest factory images. It's extracted by android-prepare-vendor.

**Comment by technonerd33** [comment]
I was digging through chroma stuff and it looks like DMService.apk includes a classes.dex.  I was unable to successfully edit system.img with the new apk, to see if that solved the issue.

https://github.com/zephiK/proprietary_vendor_huawei/blob/mm6.0/angler/proprietary/priv-app/DMService/DMService.apk

**Comment by thestinger** [comment]
There's a classes.dex in the CopperheadOS DMService.apk prebuilt too. That's not what ends up being in the release since it gets optimized.

**Comment by thestinger** [comment]
This is no longer present in the current builds. The issue can be revisited when these proprietary apps are added back again.
