### ISSUE TITLE
Pixel refuses to boot

### ISSUE THREAD

**Issue by seanlinsley** [copperhead/bugtracker#544]
I compiled from source for the Pixel, but ended up not being able to boot successfully.

I'm not sure if this is useful, but this is the only log I could figure out how to access:

<img width=30% src=https://cloud.githubusercontent.com/assets/688886/21469064/f1c69ddc-c9fc-11e6-9102-d9b6734f55c8.JPG>

I saw a number of errors while compiling. I'll recompile and document any reoccurring errors, then try installing again.

**Comment by thestinger** [comment]
The recovery log won't have anything useful.

**Comment by seanlinsley** [comment]
Is there a particular way to get information from the device? `adb bugreport` and `adb logcat` just hang.

**Comment by thestinger** [comment]
Make a userdebug build so that there's early boot adb without authentication. If it's not making it far enough for that, then the only answer is a headphone UART debug cable. The cables aren't sold anywhere that I'm aware of but they are a simple design and we might start selling them.

**Comment by seanlinsley** [comment]
Here's [compile.txt](https://github.com/copperhead/bugtracker/files/672024/compile.txt) and [install.txt](https://github.com/copperhead/bugtracker/files/672028/install.txt).

It looks like the bootloader image isn't being created successfully.

This compile was just an incremental one, this time as `userdebug`. I'll `make clean` and try again.

**Comment by seanlinsley** [comment]
[compile.txt](https://github.com/copperhead/bugtracker/files/672040/compile.txt)

It failed fairly early this time. Error message:
```
[ 10% 4495/44105] Building with Jack: ...k_intermediates/with-local/classes.dex
FAILED: /bin/bash out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/with-local/classes.dex.rsp
java.lang.AssertionError: java.util.zip.ZipException: duplicate entry: jayce/android/widget/ViewSwitcher$ViewFactory.jayce
	at com.android.sched.vfs.WriteZipFS$ZipEntryOutputStream.writeEntryIfNeeded(WriteZipFS.java:350)
	at com.android.sched.vfs.WriteZipFS$ZipEntryOutputStream.close(WriteZipFS.java:320)
	at com.android.sched.vfs.VFSToVFSWrapper.dumpToDir(VFSToVFSWrapper.java:127)
	at com.android.sched.vfs.VFSToVFSWrapper.dumpToDir(VFSToVFSWrapper.java:112)
	at com.android.sched.vfs.VFSToVFSWrapper.dumpToDir(VFSToVFSWrapper.java:112)
	at com.android.sched.vfs.VFSToVFSWrapper.dumpToDir(VFSToVFSWrapper.java:112)
	at com.android.sched.vfs.VFSToVFSWrapper.close(VFSToVFSWrapper.java:99)
	at com.android.sched.vfs.ReadWriteZipFS.close(ReadWriteZipFS.java:87)
	at com.android.sched.vfs.GenericOutputVFS.close(GenericOutputVFS.java:56)
	at com.android.jack.library.v0002.OutputJackLibraryImpl.close(OutputJackLibraryImpl.java:218)
	at com.android.jack.Jack.run(Jack.java:742)
	at com.android.jack.Jack.checkAndRun(Jack.java:412)
	at com.android.jack.CommandLine.runJack(CommandLine.java:79)
	at com.android.jack.api.v01.impl.Cli01CompilationTaskImpl.run(Cli01CompilationTaskImpl.java:85)
	at com.android.jack.server.tasks.JackTask.handle(JackTask.java:168)
	at com.android.jack.server.tasks.SynchronousServiceTask.handle(SynchronousServiceTask.java:49)
	at com.android.jack.server.tasks.JackTask.handle(JackTask.java:55)
	at com.android.jack.server.router.PathRouter.handle(PathRouter.java:65)
	at com.android.jack.server.router.ContentTypeParameterRouter.handle(ContentTypeParameterRouter.java:84)
	at com.android.jack.server.router.ContentTypeRouter.handle(ContentTypeRouter.java:82)
	at com.android.jack.server.router.ContentTypeRouter.handle(ContentTypeRouter.java:82)
	at com.android.jack.server.router.ContentTypeRouter.handle(ContentTypeRouter.java:82)
	at com.android.jack.server.router.ContentTypeParameterRouter.handle(ContentTypeParameterRouter.java:84)
	at com.android.jack.server.router.ContentTypeRouter.handle(ContentTypeRouter.java:82)
	at com.android.jack.server.router.ContentTypeRouter.handle(ContentTypeRouter.java:82)
	at com.android.jack.server.router.MethodRouter.handle(MethodRouter.java:67)
	at com.android.jack.server.router.RootContainer.handle(RootContainer.java:49)
	at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
	at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: duplicate entry: jayce/android/widget/ViewSwitcher$ViewFactory.jayce
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
	at com.android.sched.util.file.OutputZipFile$CustomZipOutputStream.putNextEntry(OutputZipFile.java:150)
	at com.android.sched.vfs.WriteZipFS$ZipEntryOutputStream.writeEntryIfNeeded(WriteZipFS.java:346)
	... 31 more

Internal compiler error (version 1.2-rc4 'Carnac' (298900 f95d7bdecfceb327f9d201a1348397ed8a843843 by android-jack-team@google.com)).
java.util.zip.ZipException: duplicate entry: jayce/android/widget/ViewSwitcher$ViewFactory.jayce.
Warning: This may have produced partial or corrupted output.
ninja: build stopped: subcommand failed.
build/core/ninja.mk:148: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

#### make failed to build some targets (36:10 (mm:ss)) ####
```

**Comment by seanlinsley** [comment]
I'm using Ubuntu, like the person here: https://code.google.com/p/android/issues/detail?id=220466

**Comment by thestinger** [comment]
The bootloader/radio images aren't bundled because these aren't supported targets yet. You need to flash the bootloader/radio images on your own from the factory images. It's *possible* it's the cause of the problem.

**Comment by thestinger** [comment]
It's just not going to be supported yet. Since we don't have any Pixel phones to test on, there's no point in trying to support it or address issues in it yet. I only set it up to the point that someone could work on it. It's not meant to actually work yet without effort put into it.

**Comment by thestinger** [comment]
#535 is one of the prerequisites. The initial work is getting a working AOSP build, not CopperheadOS.

**Comment by seanlinsley** [comment]
>You need to flash the bootloader/radio images on your own from the factory images. It's possible it's the cause of the problem.

Do you mean the images from here? https://developers.google.com/android/images

>Since we don't have any Pixel phones to test on, there's no point in trying to support it or address issues in it yet.

I already donated; hopefully y'all can afford Pixel phones to test on soon.
