### ISSUE TITLE
error: inflate: data stream error (invalid stored block lengths)

### ISSUE THREAD

**Issue by satindergrewal** [copperhead/bugtracker#791]
I'm trying to build copperhead from source for my Google Pixel, and this is the error on getting on `repo sync j32`

```shell

Fetching project platform/frameworks/opt/net/ims
Fetching project platform/external/jsilver
Fetching projects: 100% (563/563), done.  
Syncing work tree:  90% (507/563)  error: inflate: data stream error (invalid stored block lengths)
fatal: packed object 8e4156236506274e2f684ad1800ceec90a54452f (stored in .git/objects/pack/pack-647b036341979a6ab1afa1edf1289077ca921efa.pack) is corrupt
Traceback (most recent call last):
  File "/home/satinder/copperheados-OPR3.170623.008.2017.10.21.14/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/home/satinder/copperheados-OPR3.170623.008.2017.10.21.14/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/home/satinder/copperheados-OPR3.170623.008.2017.10.21.14/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/satinder/copperheados-OPR3.170623.008.2017.10.21.14/.repo/repo/subcmds/sync.py", line 821, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/home/satinder/copperheados-OPR3.170623.008.2017.10.21.14/.repo/repo/project.py", line 1327, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync)
  File "/home/satinder/copperheados-OPR3.170623.008.2017.10.21.14/.repo/repo/project.py", line 2486, in _InitWorkTree
    raise GitError("cannot initialize work tree")
error.GitError: cannot initialize work tree
satinder@ubuntu:~/copperheados-OPR3.170623.008.2017.10.21.14$ 

```

Please help.

Thanks

**Comment by thestinger** [comment]
Ask for help at https://www.reddit.com/r/CopperheadOS/. Support is only available via the customer support system, not the issue tracker.
