### ISSUE TITLE
Get error release.sh

### ISSUE THREAD

**Issue by Pycckoe** [copperhead/bugtracker#793]
When i'm enter script/release.sh sailfish
 i got error 

```
Traceback (most recent call last):
  File "build/tools/releasetools/sign_target_files_apks", line 734, in <module>
    main(sys.argv[1:])
  File "build/tools/releasetools/sign_target_files_apks", line 703, in main
    input_zip = zipfile.ZipFile(args[0], "r")
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: 'out/target/product/sailfish/obj/PACKAGING/target_files_intermediates/aosp_sailfish-target_files-OPR3.170623.008.2017.10.21.14.zip'

```
how to fix and how to create aosp_sailfish-target_files-OPR3.170623.008.2017.10.21.14.zip in this folder ?

**Comment by thestinger** [comment]
Please use https://www.reddit.com/r/CopperheadOS/ for support. This is the wrong place for it.
